# Generated by Django 3.1.7 on 2021-03-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=12)),
                ('temail', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuser', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=12)),
                ('gender', models.CharField(default='None', max_length=12)),
                ('verified', models.CharField(default='no', max_length=5)),
            ],
        ),
    ]
