# Generated by Django 3.1.7 on 2021-03-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(max_length=10)),
                ('map', models.CharField(max_length=10)),
                ('slots', models.IntegerField()),
                ('timing', models.CharField(max_length=10)),
            ],
        ),
    ]
