# Generated by Django 3.1.7 on 2021-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_match_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_data',
            name='match_name',
            field=models.CharField(default='Hello', max_length=10),
        ),
    ]
