# Generated by Django 3.1.7 on 2021-03-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_match_data_match_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_data',
            name='match_name',
            field=models.CharField(default='Hello', max_length=30),
        ),
    ]
