# Generated by Django 3.1.7 on 2021-03-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_register_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('match_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='register_match',
            name='flag_set',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
