# Generated by Django 3.1.7 on 2021-03-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210330_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_match',
            old_name='temail',
            new_name='username',
        ),
    ]
