# Generated by Django 3.1.7 on 2021-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210330_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_match',
            name='gameid',
            field=models.CharField(default='xxx', max_length=30),
        ),
        migrations.AddField(
            model_name='register_match',
            name='pwd',
            field=models.CharField(default='xxx', max_length=30),
        ),
    ]
