# Generated by Django 3.1.7 on 2021-05-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_users_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='verified',
        ),
    ]
