# Generated by Django 3.1.7 on 2021-05-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_user_data_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp_Data',
        ),
    ]
