# Generated by Django 3.1.7 on 2021-05-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_delete_otp_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_data',
            name='pricing',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='match_data',
            name='match_name',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
