# Generated by Django 3.1.7 on 2021-05-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_match_data_winning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_data',
            name='winning',
            field=models.IntegerField(default=0, max_length=70),
        ),
    ]
