# Generated by Django 3.1.7 on 2021-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210511_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_data',
            name='winning',
            field=models.CharField(default=0, max_length=70),
        ),
    ]
